In [1]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [2]:
df=pd.DataFrame({
    'color':['red','blue','green','black','white']
})
df

   color
0    red
1   blue
2  green
3  black
4  white

In [3]:
encoder=OneHotEncoder()

In [5]:
encoded=encoder.fit_transform(df[['color']]).toarray()

In [6]:
encoder_pd=pd.DataFrame(encoded,columns=encoder.get_feature_names_out())
encoder_pd

   color_black  color_blue  color_green  color_red  color_white
0          0.0         0.0          0.0        1.0          0.0
1          0.0         1.0          0.0        0.0          0.0
2          0.0         0.0          1.0        0.0          0.0
3          1.0         0.0          0.0        0.0          0.0
4          0.0         0.0          0.0        0.0          1.0